# Generated by Django 4.2.1 on 2023-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_student2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student2",
        ),
        migrations.AddField(
            model_name="student",
            name="attendances",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="classesheld",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="regnum",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
