# Generated by Django 4.2.1 on 2023-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_rename_student_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="course",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
