# Generated by Django 4.2.1 on 2023-07-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_sem1sub1att_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub1att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub1held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub2att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub2held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub3att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub3held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub4att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem1sub4held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub1att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub1held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub2att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub2held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub3att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub3held',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub4att',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem2sub4held',
        ),
    ]
