# Generated by Django 4.2.1 on 2023-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendance_sem1sub1att_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sem1sub1att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub1held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub2att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub2held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub3att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub3held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub4att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem1sub4held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub1att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub1held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub2att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub2held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub3att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub3held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub4att',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem2sub4held',
            field=models.IntegerField(default=int, max_length=100),
            preserve_default=False,
        ),
    ]
