# Generated by Django 4.2.1 on 2023-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendance_sem1sub1att_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='copyid',
            new_name='copyname',
        ),
        migrations.AddField(
            model_name='records',
            name='copycourse',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
