# Generated by Django 4.2.1 on 2023-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_records_copysub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('assignedsub1', models.CharField(max_length=100)),
                ('assignedsub2', models.CharField(max_length=100)),
                ('assignedsub3', models.CharField(max_length=100)),
                ('assignedsub4', models.CharField(max_length=100)),
                ('staffid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
